name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on a different repo. We do not need to run everything twice.
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Plugin-${{ steps.timestamp.outputs.timestamp }}
          path: build/libs/
      - name: automatic releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "${{ steps.timestamp.outputs.timestamp }}"
           prerelease: false
           title: "ViaVersion 自动构建最新版本"
           files: |
             core/target/*.jar
