name: Build and Deploy Website

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 22.x

      - name: Install dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Get the repository name
        id: get-repo-name
        run: |
          echo "::set-output name=repo_name::$(echo ${{ github.repository }} | cut -d'/' -f2)"
          
      - name: Get short SHA
        id: sha
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"    

      - name: Deploy Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ steps.get-repo-name.outputs.repo_name }}-${{ steps.sha.outputs.short_sha }}
          path: build

      - name: List files in build directory
        run: ls -la build/

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
