name: Java CI with Gradle

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@main

      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: 17
          check-latest: true

      - name: Cache Gradle Dependencies
        uses: actions/cache@main
        with:
          path: ~/.gradle/caches/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Get timestamp and short SHA
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=repo_name::$(echo ${{ github.repository }} | cut -d'/' -f2)"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Upload plugin artifact
        uses: actions/upload-artifact@main
        if: success()
        with:
          name: ${{ steps.timestamp.outputs.repo_name }}-${{ steps.timestamp.outputs.short_sha }}
          path: build/libs/*.jar

      - name: Automatic release
        if: success()
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.timestamp.outputs.timestamp }}
          prerelease: false
          title: "${{ steps.timestamp.outputs.repo_name }}-${{ steps.timestamp.outputs.short_sha }} Release"
