name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          check-latest: true

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get timestamp and short SHA
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(date +%s)"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Rename JAR file
        run: |
          for jar in build/libs/*.jar; do
            new_name="Viaversion-${{ steps.timestamp.outputs.short_sha }}.jar"
            mv "$jar" "build/libs/$new_name"
          done

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: ViaVersion-${{ steps.timestamp.outputs.short_sha }}
          path: build/libs/

      - name: Automatic release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.timestamp.outputs.timestamp }}"
          prerelease: false
          title: "ViaVersion-${{ steps.timestamp.outputs.timestamp }} Release"
          files: |
            build/libs/*.jar
